// src/style/styleDetails.js
import { StyleSheet } from "react-native";
///////////////////sarparastStyles start///////////////////////////// 
export const sarparastStyles = StyleSheet.create({
    heading: {
    fontSize: 28,
    paddingTop:4,
    paddingRight:6,
    fontFamily: "Jameel-Noori-Regular",
    color: "#6C472D",
    textAlign: "right",
    writingDirection: "rtl",
  },
  description: {
    fontSize: 20,
    paddingRight:4,
    lineHeight:30,
    color: "#6C472D",
    fontFamily: "Jameel-Noori-Regular",
    textAlign: "right",
    writingDirection: "rtl",
  },
 image_section: {
    justifyContent: "center",
    alignItems: "center",
  },
  image: {
    width: 200,
    height: 240,
  },
  });
  //////////////////// sarparastStyles end //////////////////
  //////////////////// fehrist pages style start //////////////////
export const mainStyles = StyleSheet.create({
  centerContent: {
    flex: 1,
    justifyContent: "center",
    writingDirection: "rtl",
    textAlign: "right",
    alignItems: "center",
  },
  card: {
    width: "100%",
    backgroundColor: "#E4DAC1",
    paddingVertical: 2,
    marginTop: 8,
    marginBottom: 8,
    borderRadius: 5,
    alignItems: "center",
  },
  fehristText: {
    fontSize: 20,
    fontFamily: "Jameel-Noori-Regular",
    color: "#6C472D",
    textAlign: "center",
  },
  heading: {
    fontSize: 28,
    paddingRight: 6,
    fontFamily: "Jameel-Noori-Regular",
    color: "#6C472D",
    textAlign: "right",
    writingDirection: "rtl",
  },
  noRecordText: {
    fontSize: 20,
    fontWeight: "600",
    fontFamily: "Jameel-Noori-Regular",
    color: "#6C472D",
    textAlign: "center",
    writingDirection: "rtl",
  },
  image: {
    marginTop: 10,
    width: "100%",
    height: 300,
  },
  deatilContentWrapper: {
    textAlign: "right",
    direction: "right",
    marginTop: 10,
    writingDirection: "rtl",
  },
});
 //////////////////// fehrist pages style end //////////////////
// ////////////////// blog-detail-pages style start // //////////////////
export const htmlStyles = StyleSheet.create({
  body: {
    color: "#6C472D",
    textAlign: "right",
    fontSize: 20,
    writingDirection: "rtl",
  },
  htmlBaseStyle: {
    whiteSpace: "pre-wrap",
    writingDirection: "rtl",
    textAlign: "right",
    fontFamily: "Jameel-Noori-Regular",
    color: "#6C472D",
  },
  p: {
    margin: 0,
    fontSize: 20,
    fontFamily: "Jameel-Noori-Regular",
    color: "#6C472D",
    textAlign: "right",
    writingDirection: "rtl",
    lineHeight: 30,
    whiteSpace: "pre-wrap",
  },
  span: {
    fontSize: 20,
    fontFamily: "Jameel-Noori-Regular",
    color: "#6C472D",
    textAlign: "right",
    writingDirection: "rtl",
  },
  h1: {
    fontSize: 28,
    fontFamily: "Jameel-Noori-Regular",
    color: "#6C472D",
    textAlign: "right",
    writingDirection: "rtl",
  },
  h2: {
    fontSize: 24,
    fontFamily: "Jameel-Noori-Regular",
    color: "#6C472D",
    textAlign: "right",
    writingDirection: "rtl",
  },
  h3: {
    fontSize: 22,
    fontFamily: "Jameel-Noori-Regular",
    color: "#6C472D",
    lineHeight: 30,
    marginTop:6,
    textAlign: "right",
    writingDirection: "rtl",
  },
  h4: {
    fontSize: 24,
    fontFamily: "Jameel-Noori-Regular",
    color: "#6C472D",
    lineHeight: 30,
    textAlign: "right",
    writingDirection: "rtl",
  },
  ul: {
    margin: 0,
    direction: "rtl",
    marginTop:6,
    fontFamily: "Jameel-Noori-Regular",
    color: "red",
    textAlign: "right",
    writingDirection: "rtl",
    lineHeight: 32,
  },
  ol: {
    margin: 0,
    direction: "rtl",
    fontFamily: "Jameel-Noori-Regular",
    color: "red",
    textAlign: "right",
    writingDirection: "rtl",
    lineHeight: 31,
  },
  li: {
    paddingRight: 10,
    fontFamily: "Jameel-Noori-Regular",
    color: "#6C472D",
    direction: "ltr",
    textAlign: "start",
    writingDirection: "rtl",
  },
  u: {
    textDecorationLine: "underline",
    color: "#6C472D",
    fontSize: 18,
    fontFamily: "Jameel-Noori-Regular",
    textAlign: "right",
    writingDirection: "rtl",
  },
  s: {
    textDecorationLine: "line-through",
    color: "#6C472D",
    fontSize: 20,
    lineHeight: 30,
    textAlign: "right",
    writingDirection: "rtl",
  },
  hr: {
    borderBottomColor: "#6C472D",
    borderBottomWidth: 1,
    marginVertical: 10,
  },
  br: {
    marginBottom: 10,
    padding: 40,
  },
  strong: {
    fontSize: 20,
    // marginTop:10,
    fontWeight: "bold", 
    // fontFamily: "Jameel-Noori-Regular",
    color: "red",
    lineHeight: 30,
    textAlign: "right",
    writingDirection: "rtl",
  },
});
//// /////////////////blog-detail-pages style end ////////////////////